### ISSUE TITLE
Combine command with sudo

### ISSUE THREAD

**Issue by denisshevchenko** [psibi/shell-conduit#9]
Hi!

How can I combine `sudo` (https://hackage.haskell.org/package/shell-conduit-4.6.1/docs/Data-Conduit-Shell-PATH.html#v:sudo) with some command? For example:

```
sudo ??? sed "-i" replaceProxyPass pathToNginxConfig
```

I can just run this `sed`-command, but I need sudo-permissions for it. Is it possible?

**Comment by denisshevchenko** [comment]
Yes, I know that it's possible to use command as a string-arg for `sudo`:

```
sudo "sed" "-i" replaceProxyPass pathToNginxConfig
```

But it's not so pretty... ;-)

**Comment by psibi** [comment]
Right now, there is no nice operator for it. I will see if I can add something nice. Note that you can also do something like this:

```
sudo ["sed" , "-i", replaceProxyPass, pathToNginxConfig]
```

which is better than the previous one, I think.

**Comment by denisshevchenko** [comment]
Thanks @psibi!
